# config/packages/fos_user.yaml

fos_user:
  db_driver:      orm # can be orm or odm
  firewall_name:  main
  user_class:     Sonata\UserBundle\Entity\BaseUser

  group:
    group_class:   Sonata\UserBundle\Entity\BaseGroup
    group_manager: sonata.user.orm.group_manager # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)

  service:
    user_manager: sonata.user.orm.user_manager

  from_email:
    address: "guillaume.bex44@gmil.com"
    sender_name: "guillaume.bex"